import {useEffect,useMemo,useRef} from 'react';
import {useFrame,type ThreeEvent} from '@react-three/fiber';
import {RoundedBox} from '@react-three/drei';
import * as THREE from 'three';
import type {Game} from '../data/games';
import {makeScreen} from './VitaScreen';
function Label({text,position,size=.11,color='#c9cbd2'}:{text:string;position:[number,number,number];size?:number;color?:string}){const map=useMemo(()=>{const c=document.createElement('canvas');c.width=512;c.height=100;const x=c.getContext('2d')!;x.fillStyle=color;x.font='48px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,50);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t},[text,color]);useEffect(()=>()=>map.dispose(),[map]);return <mesh position={position}><planeGeometry args={[size*5.12,size]}/><meshBasicMaterial map={map} transparent depthWrite={false}/></mesh>}
function Disc({x,y,r=.18,z=.26,rubber=false}:{x:number;y:number;r?:number;z?:number;rubber?:boolean}){return <group position={[x,y,z]} rotation={[Math.PI/2,0,0]}><mesh><cylinderGeometry args={[r,r,.07,32]}/><meshStandardMaterial color={rubber?'#121316':'#090b0f'} roughness={rubber?.75:.27}/></mesh><mesh position={[0,.04,0]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[r*.91,.012,8,40]}/><meshStandardMaterial color="#656371" metalness={.7} roughness={.3}/></mesh></group>}
export default function Vita({game,reduced,onScreen,onReady}:{game:Game|null;reduced:boolean;onScreen:()=>void;onReady:()=>void}){
const group=useRef<THREE.Group>(null);const drag=useRef({active:false,x:0,y:0,rx:0,ry:0,vx:0,vy:0,moved:0});const screen=useMemo(()=>makeScreen(game),[game]);const last=useRef(0);useEffect(()=>{if(game&&!reduced)drag.current.ry=.065},[game,reduced]);useEffect(()=>{onReady();return()=>screen.texture.dispose()},[screen,onReady]);
useFrame(({clock,pointer},dt)=>{const t=clock.elapsedTime,d=drag.current;dt=Math.min(dt,.05);if(!d.active){d.rx+=d.vx;d.ry+=d.vy;d.vx*=.84;d.vy*=.84;d.rx=THREE.MathUtils.damp(d.rx,0,2.3,dt);d.ry=THREE.MathUtils.damp(d.ry,0,2.3,dt)}d.rx=THREE.MathUtils.clamp(d.rx,-.17,.17);d.ry=THREE.MathUtils.clamp(d.ry,-.44,.44);if(group.current){group.current.rotation.x=THREE.MathUtils.damp(group.current.rotation.x,d.rx+(reduced?0:Math.sin(t*.8)*.012-pointer.y*.025),12,dt);group.current.rotation.y=THREE.MathUtils.damp(group.current.rotation.y,d.ry+(reduced?0:Math.sin(t*.65)*.025+pointer.x*.04),12,dt);group.current.rotation.z=-.018;group.current.position.y=reduced?0:Math.sin(t*.85)*.028;}if(!reduced&&t-last.current>.065){screen.draw(t);last.current=t}});
const down=(e:ThreeEvent<PointerEvent>)=>{e.stopPropagation();const d=drag.current;d.active=true;d.x=e.clientX;d.y=e.clientY;d.moved=0;d.vx=d.vy=0;(e.target as Element).setPointerCapture?.(e.pointerId)};
const move=(e:ThreeEvent<PointerEvent>)=>{const d=drag.current;if(!d.active)return;e.stopPropagation();const dx=e.clientX-d.x,dy=e.clientY-d.y;d.vy=dx*.0025;d.vx=dy*.0015;d.ry+=d.vy;d.rx+=d.vx;d.moved+=Math.abs(dx)+Math.abs(dy);d.x=e.clientX;d.y=e.clientY};
const up=(e:ThreeEvent<PointerEvent>)=>{drag.current.active=false;(e.target as Element).releasePointerCapture?.(e.pointerId)};
const shape=useMemo(()=>{const s=new THREE.Shape();s.moveTo(-2.35,-1.04);s.bezierCurveTo(-2.95,-1.03,-3.15,-.5,-3.15,0);s.bezierCurveTo(-3.15,.57,-2.97,1.02,-2.35,1.05);s.lineTo(2.35,1.05);s.bezierCurveTo(2.97,1.02,3.15,.57,3.15,0);s.bezierCurveTo(3.15,-.5,2.95,-1.03,2.35,-1.04);s.closePath();return new THREE.ExtrudeGeometry(s,{depth:.23,bevelEnabled:true,bevelSegments:5,steps:1,bevelSize:.075,bevelThickness:.055,curveSegments:24})},[]);useEffect(()=>()=>shape.dispose(),[shape]);
return <group ref={group} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current.active=false}}>
<mesh geometry={shape} position={[0,0,-.17]}><meshPhysicalMaterial color="#090a0c" metalness={.12} roughness={.23} clearcoat={1} clearcoatRoughness={.17}/></mesh>
<mesh geometry={shape} scale={[1.008,1.008,.25]} position={[0,0,-.12]}><meshStandardMaterial color="#8f8a86" metalness={.85} roughness={.27}/></mesh>
<RoundedBox args={[4.05,1.88,.09]} radius={.045} position={[0,0,.16]}><meshPhysicalMaterial color="#030405" roughness={.12} clearcoat={1}/></RoundedBox>
<mesh position={[0,.045,.215]} onClick={e=>{e.stopPropagation();if(drag.current.moved<7)onScreen()}}><planeGeometry args={[3.73,2.11*.88]}/><meshBasicMaterial map={screen.texture} toneMapped={false}/></mesh>
<Disc x={-2.49} y={.34} r={.39} z={.20}/>
{[[0,.22],[0,-.22],[-.22,0],[.22,0]].map(([x,y],i)=><group key={i}><RoundedBox args={[i<2?.20:.23,i<2?.23:.20,.085]} position={[-2.49+x,.34+y,.29]} radius={.035}><meshStandardMaterial color="#17191f" roughness={.32}/></RoundedBox><Label text={['⌃','⌄','‹','›'][i]} position={[-2.49+x,.34+y,.338]} size={.14}/></group>)}
{[[0,.28],[.28,0],[0,-.28],[-.28,0]].map(([x,y],i)=><group key={i}><Disc x={2.48+x} y={.35+y} r={.15} z={.25}/><Label text={['△','○','×','□'][i]} position={[2.48+x,.35+y,.30]} size={.20}/></group>)}
{[-2.36,2.36].map(x=><group key={x}><Disc x={x} y={-.43} r={.255} z={.23} rubber/><mesh position={[x,-.43,.295]}><sphereGeometry args={[.205,32,16]}/><meshStandardMaterial color="#15161b" roughness={.8}/></mesh><mesh position={[x,-.43,.475]}><torusGeometry args={[.15,.008,6,32]}/><meshStandardMaterial color="#35353b" roughness={.8}/></mesh></group>)}
{[-1,1].flatMap(side=>Array.from({length:6},(_,i)=><mesh key={side+':'+i} position={[side*(2.85+(i%2)*.055),-.39-Math.floor(i/2)*.075,.16]}><circleGeometry args={[.021,10]}/><meshBasicMaterial color="#010102"/></mesh>))}
<Label text="PS VITA" position={[0,-.94,.23]} size={.15}/><Label text="SONY" position={[-2.45,.85,.15]} size={.10}/>
{[2.28,2.66,-2.38].map((x,i)=><group key={x}><RoundedBox args={[.31,.12,.055]} radius={.055} position={[x,-.83,.17]}><meshStandardMaterial color="#181a22" roughness={.3}/></RoundedBox><Label text={['SELECT','START','⌂'][i]} size={i===2?.10:.045} position={[x,-.83,.206]} color={i===2?'#95b4ff':'#d0d0d5'}/></group>)}
{[-2.42,2.42].map(x=><RoundedBox key={x} args={[.8,.13,.23]} radius={.05} position={[x,1.02,-.05]}><meshStandardMaterial color="#37383c" metalness={.6} roughness={.22}/></RoundedBox>)}
<mesh position={[2.10,.77,.19]}><circleGeometry args={[.044,24]}/><meshPhysicalMaterial color="#172331" metalness={.65} roughness={.12}/></mesh>
</group>}
