import {Component,lazy,Suspense,useCallback,useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {Gamepad2,Search,UserRound,ArrowRight,Mouse,Volume2,VolumeX,Heart,Menu,X,RotateCcw} from 'lucide-react';import {games} from './data/games';import GameCarousel from './components/GameCarousel';import Modal from './components/Modal';import {useReducedMotion} from './hooks/useReducedMotion';
const Experience=lazy(()=>import('./three/Experience'));
class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?this.props.fallback:this.props.children}}
function canWebGL(){try{const c=document.createElement('canvas');const gl=c.getContext('webgl2');if(gl){gl.getExtension('WEBGL_lose_context')?.loseContext();return true}return false}catch{return false}}
export default function App(){const [selected,setSelected]=useState(4);const [screenHome,setScreenHome]=useState(true);const [loaded,setLoaded]=useState(false);const [webgl,setWebgl]=useState(canWebGL);const [modal,setModal]=useState<'memory'|'about'|'contact'|'profile'|null>(null);const [query,setQuery]=useState('');const [searchOpen,setSearchOpen]=useState(false);const [menu,setMenu]=useState(false);const [sound,setSound]=useState(false);const [saved,setSaved]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem('nostalgia-saved')||'[]');return Array.isArray(value)?value.filter(x=>typeof x==='string'):[]}catch{return []}});const reduced=useReducedMotion();const game=games[selected];const audio=useRef<AudioContext|null>(null);const stage=useRef<HTMLElement>(null);const lastWheel=useRef(0);const ready=useCallback(()=>setLoaded(true),[]);
useEffect(()=>{if(!webgl)setLoaded(true);const t=setTimeout(()=>setLoaded(true),4500);return()=>clearTimeout(t)},[webgl]);
const tick=useCallback(()=>{if(!sound)return;try{const a=audio.current??new AudioContext();audio.current=a;void a.resume();const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.setValueAtTime(640,a.currentTime);o.frequency.exponentialRampToValueAtTime(330,a.currentTime+.09);g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.1);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.11)}catch{}},[sound]);
const select=useCallback((n:number)=>{setSelected((n%9+9)%9);setScreenHome(false);tick()},[tick]);
useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(modal||['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();select(selected+(e.key==='ArrowRight'?1:-1))}if(e.key==='Escape'){setSearchOpen(false);setMenu(false)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[selected,select,modal]);
useEffect(()=>{const el=stage.current!;const fn=(e:WheelEvent)=>{if(modal||(e.target as HTMLElement).closest('.carousel,input,.search-results,dialog'))return;if(window.innerWidth<760)return;if(Math.abs(e.deltaY)<8)return;e.preventDefault();const t=Date.now();if(t-lastWheel.current>330){lastWheel.current=t;select(selected+(e.deltaY>0?1:-1))}};el.addEventListener('wheel',fn,{passive:false});return()=>el.removeEventListener('wheel',fn)},[selected,select,modal]);
useEffect(()=>{if(document.activeElement?.classList.contains('game-card'))document.querySelector<HTMLButtonElement>('.game-card.selected')?.focus()},[selected]);
function save(){const next=saved.includes(game.id)?saved.filter(x=>x!==game.id):[...saved,game.id];setSaved(next);try{localStorage.setItem('nostalgia-saved',JSON.stringify(next))}catch{}}
function screenClick(){if(screenHome){setScreenHome(false);tick()}else setModal('memory')}
const fallback=<button className="fallback" onClick={screenClick}><Gamepad2 size={52}/><span>{game.title}</span><span className="fallback-note">3D isn’t available in this browser.</span><small>Open this memory <ArrowRight size={15}/></small></button>;
const results=games.filter(g=>(g.title+' '+g.year+' '+g.genre).toLowerCase().includes(query.toLowerCase()));
return <main ref={stage} className={'experience '+(loaded?'is-ready':'')} style={{'--accent':game.accentColor} as CSSProperties} onPointerMove={e=>{if(reduced||e.pointerType!=='mouse')return;const x=(e.clientX/window.innerWidth-.5)*2,y=(e.clientY/window.innerHeight-.5)*2;stage.current?.style.setProperty('--mx',String(x));stage.current?.style.setProperty('--my',String(y))}}>
<a className="skip" href="#games">Skip to games</a><div className="room" aria-hidden="true"/><div className="room-shade" aria-hidden="true"/><div className="ambient-glow" aria-hidden="true"/><div className="crt-light" aria-hidden="true"/>
<header className="navigation"><a href="#home" className="brand" onClick={()=>{setScreenHome(true);setModal(null)}}><Gamepad2 size={31} strokeWidth={2.3}/><span>Game <em>Nostalgia</em></span></a><nav className={menu?'open':''} aria-label="Main navigation">{['Home','Games','About','Contact'].map(item=><button key={item} className={item==='Home'?'active':''} onClick={()=>{setMenu(false);if(item==='Home'){setScreenHome(true);setModal(null)}else if(item==='Games'){select(selected);document.querySelector<HTMLButtonElement>('.game-card.selected')?.focus()}else setModal(item.toLowerCase() as 'about'|'contact')}}>{item}</button>)}</nav><div className="nav-actions"><div className="search"><Search size={17}/><input aria-label="Search games" placeholder="Search your childhood..." value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true)}} onKeyDown={e=>{if(e.key==='Escape')setSearchOpen(false);if(e.key==='Enter'&&results.length){select(games.indexOf(results[0]));setSearchOpen(false);setQuery('')}}}/>{searchOpen&&<div className="search-results"><div className="search-heading">Find a familiar feeling<button aria-label="Close search" onClick={()=>setSearchOpen(false)}><X size={15}/></button></div>{results.length?results.map(g=><button key={g.id} onClick={()=>{select(games.indexOf(g));setSearchOpen(false);setQuery('')}}><span>{g.title}</span><small>{g.year}</small></button>):<p>No memories found. Try a title, year, or genre.</p>}</div>}</div><button className="circle profile" aria-label="My saved memories" onClick={()=>setModal('profile')}><UserRound size={23}/></button><button className="circle menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu/></button></div></header>
<section id="home" className="hero-copy"><div className="eyebrow"><span/> GOOD TIMES, REPLAYED</div><h1>Old Games.<br/><em>New Feelings.</em></h1><p>Relive the magic. Explore legendary games<br className="desktop-break"/> that shaped our childhood and still live<br className="desktop-break"/> in our hearts.</p><button className="cta" onClick={()=>{select(selected);document.querySelector<HTMLButtonElement>('.game-card.selected')?.focus()}}>Start Exploring <ArrowRight size={20}/></button><span className="hero-note">Your childhood is just a scroll away.</span></section>
<div className="wall-message" aria-hidden="true">Good<br/>Games<br/>Never<br/>Get Old <span>♡</span></div>
<section className="vita-stage" aria-label="Interactive 3D handheld. Drag to rotate, or use the screen button to explore." ><SceneBoundary fallback={fallback}>{webgl?<Suspense fallback={<div className="scene-loading">Waking up your handheld…</div>}><Experience game={screenHome?null:game} reduced={reduced} onScreen={screenClick} onReady={ready} onLost={()=>setWebgl(false)}/></Suspense>:fallback}</SceneBoundary><div className="vita-shadow"/><div className="vita-tools"><button aria-label="Return handheld screen to home" onClick={()=>setScreenHome(true)}><RotateCcw size={13}/> Home screen</button><button onClick={screenClick}>{screenHome?'Explore the screen':'Play Memory'} <ArrowRight size={13}/></button></div></section>
<div className="selection-label" aria-live="polite" aria-atomic="true"><span className="selection-index">{String(selected+1).padStart(2,'0')} / 09</span><strong>{game.title}</strong><span>{game.year} <i>·</i> {game.genre}</span></div>
<GameCarousel selected={selected} onSelect={select} onOpen={()=>{setScreenHome(false);setModal('memory')}}/>
<footer><div className="scroll-hint"><Mouse size={24}/><span>Scroll. Drag. Relive.</span><kbd>←</kbd><kbd>→</kbd></div><div className="journey">A Journey Through Timeless Games<div className="pagination" aria-label="Choose a game">{games.map((g,i)=><button key={g.id} aria-label={'Select '+g.title} aria-current={i===selected?'true':undefined} className={i===selected?'selected':''} onClick={()=>select(i)}/>)}</div></div><button className={'sound '+(sound?'on':'')} aria-label={sound?'Turn sound off':'Turn sound on'} aria-pressed={sound} onClick={()=>{setSound(!sound);if(!sound){try{audio.current??=new AudioContext();void audio.current.resume()}catch{}}}}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>Sound {sound?'on':'off'}</span></button></footer>
{!loaded&&<div className="loading" role="status"><Gamepad2 size={40}/><strong>GAME <em>NOSTALGIA</em></strong><p>Loading memories...</p><span className="loading-track"><i/></span></div>}
{modal&&<Modal title={modal==='memory'?game.title:modal} onClose={()=>setModal(null)}>{modal==='memory'?<><div className="eyebrow">MEMORY {String(selected+1).padStart(2,'0')} / 09</div><h2>{game.title}</h2><p className="modal-meta">{game.year} <span>•</span> {game.genre}</p><p className="memory-intro">{game.description}</p><p>{game.memory}</p><div className="memory-scene" style={{'--memory-color':game.accentColor} as CSSProperties}><Gamepad2 size={52}/><span>Remember your first time?</span><small>Some feelings never get old.</small></div><button className="cta" onClick={save}><Heart size={18} fill={saved.includes(game.id)?'currentColor':'none'}/>{saved.includes(game.id)?'Memory saved':'Save this memory'}</button><p className="fine-print">A tribute to the feeling of playing. Original games are not hosted here.</p></>:modal==='about'?<><div className="eyebrow">A LITTLE TIME MACHINE</div><h2>Games end.<br/><em>Memories stay.</em></h2><p>Game Nostalgia is a small, cozy archive of games that made ordinary afternoons unforgettable.</p><p>Pick a card. Turn the handheld in your hands. Take a moment with a game you remember.</p><p className="fine-print">An independent fan tribute. Game names belong to their respective owners. Card illustrations are original abstract tributes. This site is not affiliated with Sony or the featured game publishers.</p></>:modal==='contact'?<><div className="eyebrow">KEEP THE CONVERSATION GOING</div><h2>What game takes<br/>you back?</h2><p>Share a favorite childhood game or suggest a memory for the collection.</p><a className="cta" href="https://github.com/saaeiddev" target="_blank" rel="noreferrer">Find the creator on GitHub <ArrowRight size={18}/></a></>:<><div className="eyebrow">YOUR LITTLE COLLECTION</div><h2>Saved memories</h2><p>Keep your favorites close. Saved on this device.</p>{saved.length?<div className="saved-list">{games.filter(g=>saved.includes(g.id)).map(g=><button key={g.id} onClick={()=>{select(games.indexOf(g));setModal('memory')}}><Heart size={17}/><span>{g.title}</span><ArrowRight size={17}/></button>)}</div>:<div className="empty"><Heart size={36}/><p>Your collection is waiting.</p><span>Open a game and save your first memory.</span></div>}</>}</Modal>}
</main>}
